repos:
  - repo: local
    hooks:
      - id: frontend-check
        name: Frontend Check
        entry: frontend/scripts/pre-commit-frontend.sh
        language: script
        pass_filenames: false
        
      - id: backend-check
        name: Backend Check
        entry: backend/scripts/pre-commit-backend.sh
        language: script
        pass_filenames: false